services:
  plex:
    image: linuxserver/plex:1.41.9
    container_name: plex
    network_mode: host
    environment:
      - PUID=1100
      - PGID=1100
      - VERSION=docker
      - PLEX_MEDIA_SERVER_INFO_VENDOR=Intel
      - PLEX_MEDIA_SERVER_INFO_DEVICE=VAAPI
      - TRANSCODEDIR=/transcode
    volumes:
      - ./data:/config
      - /plex/movies:/movies
      - /plex/tv:/tv
    tmpfs:
      - /transcode:size=4g,mode=1777
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

